package main

var (
	// handledUrls 可爬取的URL
	handledUrls = [...][3]string{
		// 前缀，用于替换前缀的字符串，对应请求函数
		{"https://doi.org/", "", "requestSem"},
		{"http://doi.acm.org/", "", "requestSem"},
		{"http://doi.ieeecomputersociety.org/", "", "requestOpen"},
		{"http://link.springer.com/article/", "", "requestSem"},
		{"https://onlinelibrary.wiley.com/doi/abs/", "", "requestSem"},
		{"http://link.springer.com/chapter/", "", "requestSem"},
		{"https://www.tandfonline.com/doi/full/", "", "requestOpen"},
		{"https://www.tandfonline.com/doi/abs/", "", "requestOpen"},
		{"http://arxiv.org/abs/", "arXiv:", "requestSem"},
	}
	// unhandledUrls 不可爬取的URL
	unhandledUrls = [...]string{
		"springerlink.com/",
		"usenix.org/",
		"portal.acm.org/",
		"ieeexplore.ieee.org/",
		"ceur-ws.org/",
		"sigda.org/",
		"net.doit.wisc.edu/",
		"storageconference.org/",
		"kluweronline.com/",
		"iptps.org/",
		"journals.cambridge.org/",
		"ejournals.wspc.com.sg/",
		"journals.riverpublishers.com/",
		"www.rintonpress.com/",
		"static.cambridge.org",
		"www.cs.bham.ac.uk/",
		"dl.acm.org/",
		"www.se-hci.org/",
		"se.uwaterloo.ca/",
		"www.acm.org/",
		"netfiles.uiuc.edu/",
		"www.disi.unige.it/",
		"www.info.uni-karlsruhe.de/",
		"easychair.org/",
		"portalparts.acm.org/",
		"www.computer.org/",
		"ewic.bcs.org/",
		"scg.unibe.ch/",
		"ftp.cs.man.ac.uk/",
		"www.vldb.org/",
		"www.worldscinet.com/",
		"www.informaworld.com/",
		"gemo.futurs.inria.fr/",
		"proceedings.mlr.press/",
		"drive.google.com/",
		"www.cs.rpi.edu/",
		"www.aaai.org/",
		"www.sdsc.edu/",
		"www.cs.cmu.edu/",
		"p2pir.is.informatik.uni-duisburg.de/",
		"link.springer.com/content/pdf/",
		"www.semanticweb.org/",
		"openproceedings.org/",
		"wwwiti.cs.uni-magdeburg.de/",
		"www.edbt2000.uni-konstanz.de/",
		"epubs.siam.org/",
		"www.booksonline.iospress.nl/",
		"www.cs.ust.hk/",
		"crpit.scem.westernsydney.edu.au/",
		"www-rocq.inria.fr/",
		"www.research.att.com/",
		"db.ucsd.edu/",
		"www.cse.ogi.edu/",
		"webdb2008.como.polimi.it/",
		"webdb09.cse.buffalo.edu/",
		"webdb2011.rutgers.edu/",
		"db.disi.unitn.eu/",
		"cidrdb.org/",
		"pike.psu.edu/",
		"www.almaden.ibm.com/",
		"www.youtube.com/",
		"www-db.cs.wisc.edu/",
		"webdb2013.lille.inria.fr/",
		"ontologydesignpatterns.org/",
		"content.iospress.com/",
		"aaai.org/",
		"colt2008.cs.helsinki.fi/",
		"colt2010.haifa.il.ibm.com/",
		"dream.inf.ed.ac.uk/",
		"drops.dagstuhl.de/",
		"icml.cc/",
		"ijcai.org/",
		"jair.org/",
		"jmlr.org/",
		"nips.djvuzone.org/",
		"papers.nips.cc/",
		"projecteuclid.org/",
		"diglib.eg.org/",
		"lmcs.episciences.org/",
		"proceedings.neurips.cc/",
		"vigilworkshop.github.io/",
		"theory.lcs.mit.edu/",
		"www.ccs.neu.edu/",
		"www.cs.mcgill.ca/",
		"www.eg.org/",
		"www-formal.stanford.edu/",
		"www.isca-speech.org/",
		"www.isi.edu/",
		"www.satisfiability.org/",
		"auai.org/",
		"bioinformatics.oxfordjournals.org/",
		"bmvc2018.org/",
		"CEUR-WS.org/",
		"hdl.handle.net/",
		"jamia.bmj.com/",
		"knowledge.amia.org/",
		"metalab.unc.edu/",
		"mirw08.offis.de/",
		"research.microsoft.com/",
		"bmvc2019.org/",
		"dslpitt.org/",
		"wordpress.com/",
		"mindmodeling.org/",
		"bmvc2020-conference.com/",
		"www.dropbox.com/",
		"www.wikidata.org/",
		"textmining.krdl.org.sg/",
		"uncertainty99.microsoft.com/",
		"www10.org/",
		"www2003.org/",
		"www2013.org/",
		"www.biomedcentral.com/",
		"www.bmva.org/",
		"www.comp.nus.edu.sg/",
		"ww.cs.caltech.edu/",
		"www.ep.liu.se/",
		"www.gatsby.ucl.ac.uk/",
		"www.graphicsinterface.org/",
		"www.w3j.com/",
		"www.w3.org/",
		"conferences.sigcomm.org/",
		"dl.gi.de/",
		"www.ndss-symposium.org/",
		"wp.internetsociety.org/",
		"www.cs.virginia.edu/",
		"www.dfrws.org/",
		"www.raid-symposium.org/",
		"www.read.cs.ucla.edu/",
		"aclweb.org/",
		"openaccess.thecvf.com/",
		"dl.ifip.org/",
	}
)
